# Generated by Django 4.1.7 on 2023-03-04 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_name', models.CharField(max_length=100)),
                ('dep_description', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Home',
        ),
    ]
