# Generated by Django 4.1.7 on 2023-03-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_doctors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='dep_description',
            field=models.TextField(max_length=255),
        ),
    ]
