# Generated by Django 4.1.7 on 2023-03-06 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking_data',
            new_name='booking_date',
        ),
    ]
